worker_processes 1;
pid /tmp/nginx.pid;

error_log /dev/stderr info;

events {
	worker_connections 512;
}

rtmp {
	server {
		listen 1935;
		chunk_size 4096;
		max_connections 8;

		ping 30s;
		ping_timeout 10s;

		include access.conf;

		application restream {
			live on;
			record off;
			meta copy;

			push_reconnect 3s;

			# Reject publish when no known platform arg is present
			dynamic_push_required off;

			# Reject publish when any platform push fails to connect
			dynamic_push_strict off;

			# Maximum stream key length accepted from the client URL
			dynamic_push_key_max_len 512;

			# Pass stream keys as RTMP query args:
			#   rtmp://server:1935/restream/live?yt=KEY&tw=KEY
			#
			# Add platforms you want to push to.

			dynamic_push_arg yt  rtmp://a.rtmp.youtube.com/live2;
			dynamic_push_arg tw  rtmp://live.twitch.tv/app;
			dynamic_push_arg fb  rtmps://live-api-s.facebook.com:443/rtmp;
			dynamic_push_arg vk  rtmp://ovsu.mycdn.me/input;
			dynamic_push_arg tr  rtmp://livepush.trovo.live/live;
			dynamic_push_arg kk  rtmps://ingest.global-contribute.live-video.net/app;
		}
	}
}

include stats.conf;
