http {
	client_body_temp_path /tmp/client_body_temp;

	server {
		listen 8080;

		include access.conf;

		location = /stat.xsl {
			root /share/html;
		}

		location / {
			rtmp_stat all;
			rtmp_stat_stylesheet /stat.xsl;
		}

		location /control {
			rtmp_control all;
		}
	}
}
